In [5]:
import pandas as pd

In [6]:
import warnings 
warnings.filterwarnings("ignore")

In [7]:
#load data
data=pd.read_csv("creditcard.csv")

# Data Preprocessing

In [8]:
data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [9]:
data.shape

(284807, 31)

In [10]:
data.columns

Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount',
       'Class'],
      dtype='object')

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [12]:
data.isna().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [13]:
data.duplicated().sum()

np.int64(1081)

In [14]:
data.drop_duplicates(inplace=True,ignore_index=True)  #ignore index can resets the index of the dataframe

In [15]:
data.corr()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
Time,1.000000,0.117927,-0.010556,-0.422054,-0.105845,0.173223,-0.063279,0.085335,-0.038203,-0.007861,...,0.045913,0.143727,0.051474,-0.015954,-0.233262,-0.041818,-0.005171,-0.009305,-0.010559,-0.012359
V1,0.117927,1.000000,0.006875,-0.008112,0.002257,-0.007036,0.000413,-0.009173,-0.001168,0.001828,...,0.002818,-0.001436,-0.001330,-0.000723,-0.000222,-0.000684,-0.015706,-0.004861,-0.230105,-0.094486
V2,-0.010556,0.006875,1.000000,0.005278,-0.001495,0.005210,-0.000594,0.007425,0.002899,-0.000274,...,-0.004897,0.001237,-0.003855,0.000701,-0.001569,0.000253,0.007555,0.001611,-0.533428,0.084624
V3,-0.422054,-0.008112,0.005278,1.000000,0.002829,-0.006879,-0.001511,-0.011721,-0.001815,-0.003579,...,0.003500,-0.000275,0.000449,-0.000072,0.000425,-0.000094,-0.007051,-0.000134,-0.212410,-0.182322
V4,-0.105845,0.002257,-0.001495,0.002829,1.000000,0.001744,-0.000880,0.004657,0.000890,0.002154,...,-0.001034,0.000115,0.000732,-0.000120,0.000162,0.000777,0.001322,0.000231,0.099514,0.129326
V5,0.173223,-0.007036,0.005210,-0.006879,0.001744,1.000000,-0.000938,-0.008709,0.001430,-0.001213,...,0.001622,-0.000559,0.001183,0.000198,0.000069,0.000390,-0.005798,-0.000820,-0.387685,-0.087812
V6,-0.063279,0.000413,-0.000594,-0.001511,-0.000880,-0.000938,1.000000,0.000436,0.003036,-0.000734,...,-0.002134,0.001104,-0.000755,0.001202,0.000697,-0.000028,0.000289,0.000925,0.216389,-0.043915
V7,0.085335,-0.009173,0.007425,-0.011721,0.004657,-0.008709,0.000436,1.000000,-0.006419,-0.004921,...,0.009010,-0.002280,0.003303,-0.000384,-0.000072,0.000624,-0.004537,0.001657,0.400408,-0.172347
V8,-0.038203,-0.001168,0.002899,-0.001815,0.000890,0.001430,0.003036,-0.006419,1.000000,0.001038,...,0.018892,-0.006156,0.004994,0.000113,0.000011,-0.001407,0.000613,-0.000099,-0.104662,0.033068
V9,-0.007861,0.001828,-0.000274,-0.003579,0.002154,-0.001213,-0.000734,-0.004921,0.001038,1.000000,...,0.000679,0.000785,0.000677,-0.000103,-0.000275,0.001253,0.008221,0.005591,-0.044123,-0.094021
V10,0.031068,0.000815,0.000620,-0.009632,0.002753,-0.006050,-0.002180,-0.013617,0.000481,-0.012613,...,0.003777,-0.000481,0.001917,0.000154,-0.000565,0.001089,0.010769,0.009159,-0.102255,-0.206971
V11,-0.248536,0.001028,-0.000633,0.002339,-0.001223,0.000411,-0.000211,0.002454,0.004688,-0.000217,...,-0.002760,-0.000150,-0.000037,0.000080,0.000047,-0.000204,0.001987,0.002562,-0.000015,0.149067
V12,0.125500,-0.001524,0.002266,-0.005900,0.003366,-0.002342,-0.001185,-0.006153,-0.004414,-0.002385,...,0.003285,0.000151,0.000486,0.000588,-0.000181,-0.000138,-0.000929,-0.000613,-0.009254,-0.250711
V13,-0.065958,-0.000568,0.000680,0.000113,0.000177,0.000019,0.000397,-0.000170,-0.001381,0.000745,...,0.000522,0.000016,0.000252,-0.000049,0.000248,-0.000101,-0.001577,-0.000604,0.005209,-0.003897
V14,-0.100316,-0.002663,0.002711,-0.003027,0.002801,-0.001000,0.000184,-0.003816,-0.008387,0.001981,...,0.005633,-0.001906,0.000666,-0.000026,0.000155,-0.000702,-0.004556,-0.004664,0.034122,-0.293375
V15,-0.184392,-0.000602,0.001538,-0.001230,0.000572,-0.001171,-0.000470,-0.001394,0.001044,-0.000283,...,-0.000271,-0.001197,0.000969,0.000113,0.000445,-0.002034,-0.000641,0.000858,-0.003265,-0.003300
V16,0.011286,-0.003345,0.004013,-0.004430,0.003346,-0.002373,0.000122,-0.005944,-0.004376,-0.000086,...,0.004326,-0.000820,0.001209,-0.000482,0.000215,-0.001245,-0.003974,-0.001629,-0.004488,-0.187186
V17,-0.073819,-0.003491,0.003244,-0.008159,0.003655,-0.004466,-0.001716,-0.008794,-0.005576,-0.002318,...,0.003560,-0.000162,0.000667,0.001006,-0.000685,0.000157,-0.003421,-0.002703,0.007730,-0.313498
V18,0.090305,-0.003535,0.002477,-0.003495,0.002325,-0.002685,0.000541,-0.004279,-0.001323,-0.000373,...,0.001629,-0.000533,0.000240,-0.000710,-0.000559,-0.000596,-0.004231,-0.001256,0.035775,-0.105340
V19,0.029537,0.000919,-0.000358,-0.000016,-0.000560,0.000436,0.000106,0.000846,-0.000626,0.000247,...,0.000244,0.001342,0.000381,-0.000112,-0.000084,0.000856,-0.000544,0.000353,-0.055994,0.033631
V20,-0.051022,-0.001393,-0.001287,-0.002269,0.000318,-0.001185,-0.000181,-0.001192,0.000271,-0.001838,...,0.005372,-0.001617,-0.001094,-0.000303,-0.000643,-0.000310,-0.000049,0.002671,0.340729,0.021486
V21,0.045913,0.002818,-0.004897,0.003500,-0.001034,0.001622,-0.002134,0.009010,0.018892,0.000679,...,1.000000,0.009645,-0.006391,0.001210,-0.000872,-0.000874,-0.005216,-0.004436,0.108058,0.026357
V22,0.143727,-0.001436,0.001237,-0.000275,0.000115,-0.000559,0.001104,-0.002280,-0.006156,0.000785,...,0.009645,1.000000,0.001929,-0.000031,0.000197,-0.001495,0.003037,0.001392,-0.064965,0.004887
V23,0.051474,-0.001330,-0.003855,0.000449,0.000732,0.001183,-0.000755,0.003303,0.004994,0.000677,...,-0.006391,0.001929,1.000000,0.000273,-0.000532,-0.000185,-0.002028,-0.003224,-0.112833,-0.006333
V24,-0.015954,-0.000723,0.000701,-0.000072,-0.000120,0.000198,0.001202,-0.000384,0.000113,-0.000103,...,0.001210,-0.000031,0.000273,1.000000,-0.000188,0.000568,-0.000885,0.000322,0.005055,-0.007210
V25,-0.233262,-0.000222,-0.001569,0.000425,0.000162,0.000069,0.000697,-0.000072,0.000011,-0.000275,...,-0.000872,0.000197,-0.000532,-0.000188,1.000000,0.000048,-0.001339,-0.000565,-0.047596,0.003202
V26,-0.041818,-0.000684,0.000253,-0.000094,0.000777,0.000390,-0.000028,0.000624,-0.001407,0.001253,...,-0.000874,-0.001495,-0.000185,0.000568,0.000048,1.000000,-0.003294,-0.000999,-0.003425,0.004265
V27,-0.005171,-0.015706,0.007555,-0.007051,0.001322,-0.005798,0.000289,-0.004537,0.000613,0.008221,...,-0.005216,0.003037,-0.002028,-0.000885,-0.001339,-0.003294,1.000000,-0.013950,0.027922,0.021892
V28,-0.009305,-0.004861,0.001611,-0.000134,0.000231,-0.000820,0.000925,0.001657,-0.000099,0.005591,...,-0.004436,0.001392,-0.003224,0.000322,-0.000565,-0.000999,-0.013950,1.000000,0.010143,0.009682
Amount,-0.010559,-0.230105,-0.533428,-0.212410,0.099514,-0.387685,0.216389,0.400408,-0.104662,-0.044123,...,0.108058,-0.064965,-0.112833,0.005055,-0.047596,-0.003425,0.027922,0.010143,1.000000,0.005777
Class,-0.012359,-0.094486,0.084624,-0.182322,0.129326,-0.087812,-0.043915,-0.172347,0.033068,-0.094021,...,0.026357,0.004887,-0.006333,-0.007210,0.003202,0.004265,0.021892,0.009682,0.005777,1.000000

In [16]:
#breaking our data into X and y
X=data.drop("Class",axis=1)
y=data.Class

In [17]:
y.value_counts()

Class
0    283253
1       473
Name: count, dtype: int64

In [18]:
#Lets we can train-test split our Data
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=123)

## Data Balancing

In [19]:
#Lets we can use the SMOTE
from imblearn.over_sampling import SMOTE
smote=SMOTE(sampling_strategy="minority",random_state=0)

In [20]:
X_train,y_train=smote.fit_resample(X_train,y_train)

In [21]:
X_train.shape

(424890, 30)

In [22]:
y_train.value_counts()

Class
0    212445
1    212445
Name: count, dtype: int64

In [23]:
X_train,X_val,y_train,y_val=train_test_split(X_train,y_train,test_size=0.20,stratify=y_train,random_state=42)  #stratify=y_train means that make the proportion of test(validation) ,according to the proportion of y_train.

## Apply Normalization and Standardization Scaling On our Data

In [24]:
from sklearn.preprocessing import MinMaxScaler,StandardScaler

In [25]:
#Normalization
mmscaler=MinMaxScaler()
mmscaled_train=mmscaler.fit_transform(X_train)
mmscaled_test=mmscaler.transform(X_test)

In [26]:
#Standardization
stscaler=StandardScaler()
stscaled_train=stscaler.fit_transform(X_train)
stscaled_val=stscaler.transform(X_val)
stscaled_test=stscaler.transform(X_test)

# Applying Our ANN Model

In [27]:
#Importing Libraries
from tensorflow import keras
from keras import layers

In [28]:
# model_ar=keras.Sequential([
#     layers.Input(shape=(X_train.shape[1],)),  #Or (30,)
#     layers.Dense(32,activation="relu"),
#     layers.Dense(16,activation="relu"),
#     layers.Dense(1,activation="sigmoid")

# ])

In [29]:
# model_ar.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy","precision","recall"])

In [30]:
def create_model(activation, optimizer):
    model = keras.Sequential([
        layers.Input((X_train.shape[-1],)),
        layers.Dense(64,activation=activation),
        layers.Dense(32, activation=activation),
        layers.Dense(16, activation=activation),
        layers.Dense(8,activation=activation),
        layers.Dense(1, activation="sigmoid")
    ])

    model.compile(
        optimizer=optimizer,
        loss="binary_crossentropy",
        metrics=["accuracy","precision","recall"]
    )

    return model

Standardization scaling can works better on our model

In [31]:
#model_ar.fit(stscaled_train,y_train,epochs=20,validation_split=0.20,batch_size=128)
#model_ar.fit(stscaled_train,y_train,epochs=50,validation_split=0.20,batch_size=128)
# model_ar.fit(stscaled_train,y_train,epochs=100,validation_split=0.20,batch_size=128)

## Model1 Fitting

In [32]:
# model1_20 = create_model("relu", "adam")

# model1_20.fit(
#     stscaled_train,
#     y_train,
#     epochs=20,
#     validation_data=(stscaled_val,y_val),
#     batch_size=128
# )

In [33]:
model1_50 = create_model("relu", "adam")

model1_50.fit(
    stscaled_train,
    y_train,
    epochs=50,
    validation_data=(stscaled_val,y_val),
    batch_size=128

)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.
Epoch 1/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 3ms/step - accuracy: 0.9881 - loss: 0.0355 - precision: 0.9921 - recall: 0.9841 - val_accuracy: 0.9980 - val_loss: 0.0075 - val_precision: 0.9962 - val_recall: 0.9998
Epoch 2/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - accuracy: 0.9985 - loss: 0.0057 - precision: 0.9979 - recall: 0.9991 - val_accuracy: 0.9991 - val_loss: 0.0034 - val_precision: 0.9982 - val_recall: 1.0000
Epoch 3/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - accuracy: 0.9990 - loss: 0.0040 - precision: 0.9985 - recall: 0.9994 - val_accuracy: 0.9989 - val_loss: 0.0039 - val_precision: 0.9987 - val_recall: 0.9992
Epoch 4/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - accuracy: 0.9991 - loss: 0.0034 - precision: 0.9988 - recall: 0.9995 - val_accuracy: 0.9989 - val_loss: 0.0041 - val_precision: 0.9979 - val_recall: 1.0000
Epoch 5/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - accuracy: 0.9992 - loss: 0.0030 - precision: 0.9989 - recall: 0.9995 - val_accuracy: 0.9993 - val_loss: 0.0029 - val_precision: 0.9987 - val_recall: 1.0000
Epoch 6/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9993 - loss: 0.0025 - precision: 0.9991 - recall: 0.9995 - val_accuracy: 0.9992 - val_loss: 0.0033 - val_precision: 0.9986 - val_recall: 0.9997
Epoch 7/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9994 - loss: 0.0021 - precision: 0.9992 - recall: 0.9997 - val_accuracy: 0.9994 - val_loss: 0.0024 - val_precision: 0.9994 - val_recall: 0.9994
Epoch 8/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - accuracy: 0.9995 - loss: 0.0020 - precision: 0.9993 - recall: 0.9997 - val_accuracy: 0.9994 - val_loss: 0.0020 - val_precision: 0.9988 - val_recall: 1.0000
Epoch 9/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - accuracy: 0.9995 - loss: 0.0018 - precision: 0.9994 - recall: 0.9997 - val_accuracy: 0.9993 - val_loss: 0.0023 - val_precision: 0.9994 - val_recall: 0.9993
Epoch 10/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - accuracy: 0.9996 - loss: 0.0015 - precision: 0.9994 - recall: 0.9997 - val_accuracy: 0.9994 - val_loss: 0.0024 - val_precision: 0.9988 - val_recall: 1.0000
Epoch 11/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 18s 4ms/step - accuracy: 0.9996 - loss: 0.0015 - precision: 0.9995 - recall: 0.9997 - val_accuracy: 0.9993 - val_loss: 0.0026 - val_precision: 0.9988 - val_recall: 0.9999
Epoch 12/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - accuracy: 0.9996 - loss: 0.0014 - precision: 0.9995 - recall: 0.9998 - val_accuracy: 0.9996 - val_loss: 0.0017 - val_precision: 0.9991 - val_recall: 1.0000
Epoch 13/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.9996 - loss: 0.0013 - precision: 0.9995 - recall: 0.9997 - val_accuracy: 0.9996 - val_loss: 0.0017 - val_precision: 0.9992 - val_recall: 1.0000
Epoch 14/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9996 - loss: 0.0012 - precision: 0.9995 - recall: 0.9998 - val_accuracy: 0.9995 - val_loss: 0.0017 - val_precision: 0.9994 - val_recall: 0.9996
Epoch 15/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9996 - loss: 0.0013 - precision: 0.9995 - recall: 0.9998 - val_accuracy: 0.9997 - val_loss: 0.0016 - val_precision: 0.9994 - val_recall: 1.0000
Epoch 16/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9997 - loss: 9.1545e-04 - precision: 0.9996 - recall: 0.9998 - val_accuracy: 0.9997 - val_loss: 0.0013 - val_precision: 0.9994 - val_recall: 1.0000
Epoch 17/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 11s 3ms/step - accuracy: 0.9996 - loss: 0.0011 - precision: 0.9995 - recall: 0.9997 - val_accuracy: 0.9997 - val_loss: 0.0019 - val_precision: 0.9994 - val_recall: 1.0000
Epoch 18/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - accuracy: 0.9997 - loss: 8.2994e-04 - precision: 0.9996 - recall: 0.9998 - val_accuracy: 0.9998 - val_loss: 0.0014 - val_precision: 0.9995 - val_recall: 1.0000
Epoch 19/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9997 - loss: 9.6374e-04 - precision: 0.9996 - recall: 0.9998 - val_accuracy: 0.9996 - val_loss: 0.0023 - val_precision: 0.9992 - val_recall: 1.0000
Epoch 20/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9997 - loss: 9.3528e-04 - precision: 0.9996 - recall: 0.9999 - val_accuracy: 0.9993 - val_loss: 0.0032 - val_precision: 0.9986 - val_recall: 1.0000
Epoch 21/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9998 - loss: 7.7640e-04 - precision: 0.9997 - recall: 0.9999 - val_accuracy: 0.9982 - val_loss: 0.0064 - val_precision: 0.9991 - val_recall: 0.9973
Epoch 22/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9997 - loss: 9.1141e-04 - precision: 0.9996 - recall: 0.9998 - val_accuracy: 0.9997 - val_loss: 0.0014 - val_precision: 0.9994 - val_recall: 1.0000
Epoch 23/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9998 - loss: 7.5199e-04 - precision: 0.9997 - recall: 0.9998 - val_accuracy: 0.9996 - val_loss: 0.0019 - val_precision: 0.9992 - val_recall: 1.0000
Epoch 24/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - accuracy: 0.9997 - loss: 7.8505e-04 - precision: 0.9997 - recall: 0.9998 - val_accuracy: 0.9997 - val_loss: 0.0018 - val_precision: 0.9994 - val_recall: 1.0000
Epoch 25/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.9998 - loss: 5.7778e-04 - precision: 0.9998 - recall: 0.9999 - val_accuracy: 0.9998 - val_loss: 0.0017 - val_precision: 0.9995 - val_recall: 1.0000
Epoch 26/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - accuracy: 0.9998 - loss: 8.2997e-04 - precision: 0.9997 - recall: 0.9998 - val_accuracy: 0.9997 - val_loss: 0.0029 - val_precision: 0.9995 - val_recall: 1.0000
Epoch 28/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9998 - loss: 7.7865e-04 - precision: 0.9997 - recall: 0.9998 - val_accuracy: 0.9995 - val_loss: 0.0028 - val_precision: 0.9990 - val_recall: 1.0000
Epoch 29/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - accuracy: 0.9999 - loss: 3.7753e-04 - precision: 0.9999 - recall: 0.9999 - val_accuracy: 0.9996 - val_loss: 0.0021 - val_precision: 0.9996 - val_recall: 0.9996
Epoch 30/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 23s 8ms/step - accuracy: 0.9998 - loss: 7.2441e-04 - precision: 0.9998 - recall: 0.9998 - val_accuracy: 0.9995 - val_loss: 0.0035 - val_precision: 0.9991 - val_recall: 1.0000
Epoch 31/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - accuracy: 0.9998 - loss: 5.3529e-04 - precision: 0.9998 - recall: 0.9999 - val_accuracy: 0.9995 - val_loss: 0.0023 - val_precision: 0.9994 - val_recall: 0.9996
Epoch 32/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9998 - loss: 6.4271e-04 - precision: 0.9998 - recall: 0.9999 - val_accuracy: 0.9998 - val_loss: 0.0011 - val_precision: 0.9996 - val_recall: 1.0000
Epoch 33/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - accuracy: 0.9998 - loss: 6.8572e-04 - precision: 0.9998 - recall: 0.9999 - val_accuracy: 0.9998 - val_loss: 0.0014 - val_precision: 0.9995 - val_recall: 1.0000
Epoch 34/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - accuracy: 0.9998 - loss: 4.9721e-04 - precision: 0.9998 - recall: 0.9999 - val_accuracy: 0.9997 - val_loss: 0.0021 - val_precision: 0.9995 - val_recall: 1.0000
Epoch 35/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - accuracy: 0.9999 - loss: 5.1376e-04 - precision: 0.9998 - recall: 0.9999 - val_accuracy: 0.9998 - val_loss: 0.0021 - val_precision: 0.9996 - val_recall: 1.0000
Epoch 36/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - accuracy: 0.9998 - loss: 5.8052e-04 - precision: 0.9998 - recall: 0.9999 - val_accuracy: 0.9998 - val_loss: 0.0025 - val_precision: 0.9996 - val_recall: 1.0000
Epoch 37/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9998 - loss: 6.0202e-04 - precision: 0.9998 - recall: 0.9998 - val_accuracy: 0.9996 - val_loss: 0.0024 - val_precision: 0.9995 - val_recall: 0.9998
Epoch 38/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9999 - loss: 4.2127e-04 - precision: 0.9999 - recall: 0.9999 - val_accuracy: 0.9994 - val_loss: 0.0038 - val_precision: 0.9988 - val_recall: 1.0000
Epoch 39/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - accuracy: 0.9999 - loss: 6.3611e-04 - precision: 0.9998 - recall: 0.9999 - val_accuracy: 0.9999 - val_loss: 0.0013 - val_precision: 0.9997 - val_recall: 1.0000
Epoch 40/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - accuracy: 0.9999 - loss: 5.0075e-04 - precision: 0.9999 - recall: 0.9999 - val_accuracy: 0.9997 - val_loss: 0.0021 - val_precision: 0.9994 - val_recall: 1.0000
Epoch 41/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - accuracy: 0.9999 - loss: 5.1277e-04 - precision: 0.9999 - recall: 0.9999 - val_accuracy: 0.9998 - val_loss: 0.0020 - val_precision: 0.9996 - val_recall: 1.0000
Epoch 42/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - accuracy: 0.9999 - loss: 5.3734e-04 - precision: 0.9999 - recall: 0.9999 - val_accuracy: 0.9998 - val_loss: 0.0014 - val_precision: 0.9997 - val_recall: 1.0000
Epoch 43/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9999 - loss: 3.0381e-04 - precision: 0.9999 - recall: 0.9999 - val_accuracy: 0.9998 - val_loss: 0.0017 - val_precision: 0.9996 - val_recall: 1.0000
Epoch 44/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - accuracy: 0.9999 - loss: 8.1997e-04 - precision: 0.9998 - recall: 0.9999 - val_accuracy: 0.9997 - val_loss: 0.0016 - val_precision: 0.9994 - val_recall: 1.0000
Epoch 45/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - accuracy: 0.9999 - loss: 4.7207e-04 - precision: 0.9999 - recall: 0.9998 - val_accuracy: 0.9995 - val_loss: 0.0027 - val_precision: 0.9990 - val_recall: 1.0000
Epoch 46/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - accuracy: 0.9999 - loss: 5.0062e-04 - precision: 0.9998 - recall: 0.9999 - val_accuracy: 0.9998 - val_loss: 0.0014 - val_precision: 0.9997 - val_recall: 1.0000
Epoch 47/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9999 - loss: 2.7353e-04 - precision: 0.9999 - recall: 0.9999 - val_accuracy: 0.9998 - val_loss: 0.0014 - val_precision: 0.9997 - val_recall: 1.0000
Epoch 48/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9999 - loss: 5.9925e-04 - precision: 0.9999 - recall: 0.9999 - val_accuracy: 0.9998 - val_loss: 0.0017 - val_precision: 0.9996 - val_recall: 1.0000
Epoch 49/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - accuracy: 0.9999 - loss: 5.7347e-04 - precision: 0.9998 - recall: 0.9999 - val_accuracy: 0.9997 - val_loss: 0.0020 - val_precision: 0.9994 - val_recall: 1.0000
Epoch 50/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - accuracy: 0.9999 - loss: 3.9776e-04 - precision: 0.9999 - recall: 0.9999 - val_accuracy: 0.9997 - val_loss: 0.0016 - val_precision: 0.9996 - val_recall: 0.9997

## Model2 Fiting

In [42]:
model2_50 = create_model("tanh", "sgd")

model2_50.fit(
    stscaled_train,
    y_train,
    epochs=50,
    validation_data=(stscaled_val,y_val),
    batch_size=128

)

Epoch 1/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - accuracy: 0.9580 - loss: 0.1204 - precision: 0.9786 - recall: 0.9364 - val_accuracy: 0.9724 - val_loss: 0.0761 - val_precision: 0.9822 - val_recall: 0.9622
Epoch 2/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9775 - loss: 0.0639 - precision: 0.9838 - recall: 0.9710 - val_accuracy: 0.9815 - val_loss: 0.0530 - val_precision: 0.9858 - val_recall: 0.9771
Epoch 3/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9839 - loss: 0.0458 - precision: 0.9879 - recall: 0.9798 - val_accuracy: 0.9870 - val_loss: 0.0385 - val_precision: 0.9890 - val_recall: 0.9850
Epoch 4/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9883 - loss: 0.0334 - precision: 0.9906 - recall: 0.9860 - val_accuracy: 0.9911 - val_loss: 0.0285 - val_precision: 0.9907 - val_recall: 0.9916
Epoch 5/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9918 - loss: 0.0250 - precision: 0.9926 - recall: 0.9910 - val_accuracy: 0.9936 - val_loss: 0.0218 - val_precision: 0.9932 - val_recall: 0.9940
Epoch 6/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9941 - loss: 0.0194 - precision: 0.9940 - recall: 0.9942 - val_accuracy: 0.9947 - val_loss: 0.0176 - val_precision: 0.9947 - val_recall: 0.9947
Epoch 7/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - accuracy: 0.9955 - loss: 0.0158 - precision: 0.9949 - recall: 0.9961 - val_accuracy: 0.9963 - val_loss: 0.0144 - val_precision: 0.9949 - val_recall: 0.9978
Epoch 8/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9964 - loss: 0.0130 - precision: 0.9958 - recall: 0.9971 - val_accuracy: 0.9969 - val_loss: 0.0123 - val_precision: 0.9954 - val_recall: 0.9984
Epoch 9/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9971 - loss: 0.0109 - precision: 0.9963 - recall: 0.9979 - val_accuracy: 0.9973 - val_loss: 0.0113 - val_precision: 0.9953 - val_recall: 0.9993
Epoch 10/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9976 - loss: 0.0094 - precision: 0.9968 - recall: 0.9984 - val_accuracy: 0.9973 - val_loss: 0.0097 - val_precision: 0.9955 - val_recall: 0.9992
Epoch 11/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9979 - loss: 0.0083 - precision: 0.9971 - recall: 0.9987 - val_accuracy: 0.9980 - val_loss: 0.0086 - val_precision: 0.9973 - val_recall: 0.9988
Epoch 12/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9981 - loss: 0.0074 - precision: 0.9974 - recall: 0.9989 - val_accuracy: 0.9981 - val_loss: 0.0080 - val_precision: 0.9964 - val_recall: 0.9998
Epoch 13/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9985 - loss: 0.0066 - precision: 0.9977 - recall: 0.9993 - val_accuracy: 0.9972 - val_loss: 0.0086 - val_precision: 0.9981 - val_recall: 0.9964
Epoch 14/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9986 - loss: 0.0062 - precision: 0.9978 - recall: 0.9993 - val_accuracy: 0.9984 - val_loss: 0.0068 - val_precision: 0.9971 - val_recall: 0.9998
Epoch 15/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9988 - loss: 0.0057 - precision: 0.9980 - recall: 0.9995 - val_accuracy: 0.9986 - val_loss: 0.0064 - val_precision: 0.9973 - val_recall: 0.9999
Epoch 16/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9989 - loss: 0.0053 - precision: 0.9981 - recall: 0.9996 - val_accuracy: 0.9985 - val_loss: 0.0065 - val_precision: 0.9977 - val_recall: 0.9993
Epoch 17/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9990 - loss: 0.0050 - precision: 0.9983 - recall: 0.9996 - val_accuracy: 0.9986 - val_loss: 0.0060 - val_precision: 0.9976 - val_recall: 0.9996
Epoch 18/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9990 - loss: 0.0047 - precision: 0.9984 - recall: 0.9997 - val_accuracy: 0.9986 - val_loss: 0.0061 - val_precision: 0.9972 - val_recall: 1.0000
Epoch 19/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9990 - loss: 0.0045 - precision: 0.9984 - recall: 0.9997 - val_accuracy: 0.9984 - val_loss: 0.0062 - val_precision: 0.9968 - val_recall: 1.0000
Epoch 20/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9991 - loss: 0.0043 - precision: 0.9985 - recall: 0.9997 - val_accuracy: 0.9986 - val_loss: 0.0056 - val_precision: 0.9973 - val_recall: 1.0000
Epoch 21/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9992 - loss: 0.0041 - precision: 0.9987 - recall: 0.9998 - val_accuracy: 0.9990 - val_loss: 0.0051 - val_precision: 0.9981 - val_recall: 0.9999
Epoch 22/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9992 - loss: 0.0039 - precision: 0.9987 - recall: 0.9997 - val_accuracy: 0.9988 - val_loss: 0.0053 - val_precision: 0.9977 - val_recall: 0.9999
Epoch 23/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9993 - loss: 0.0037 - precision: 0.9987 - recall: 0.9998 - val_accuracy: 0.9993 - val_loss: 0.0054 - val_precision: 0.9988 - val_recall: 0.9999
Epoch 24/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9993 - loss: 0.0037 - precision: 0.9987 - recall: 0.9998 - val_accuracy: 0.9986 - val_loss: 0.0058 - val_precision: 0.9987 - val_recall: 0.9984
Epoch 25/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9993 - loss: 0.0035 - precision: 0.9988 - recall: 0.9998 - val_accuracy: 0.9988 - val_loss: 0.0051 - val_precision: 0.9976 - val_recall: 1.0000
Epoch 26/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9993 - loss: 0.0034 - precision: 0.9989 - recall: 0.9998 - val_accuracy: 0.9991 - val_loss: 0.0049 - val_precision: 0.9982 - val_recall: 1.0000
Epoch 27/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9994 - loss: 0.0033 - precision: 0.9989 - recall: 0.9998 - val_accuracy: 0.9990 - val_loss: 0.0049 - val_precision: 0.9981 - val_recall: 1.0000
Epoch 28/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9994 - loss: 0.0032 - precision: 0.9990 - recall: 0.9999 - val_accuracy: 0.9990 - val_loss: 0.0048 - val_precision: 0.9980 - val_recall: 1.0000
Epoch 29/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9995 - loss: 0.0031 - precision: 0.9990 - recall: 0.9999 - val_accuracy: 0.9991 - val_loss: 0.0046 - val_precision: 0.9981 - val_recall: 1.0000
Epoch 30/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9994 - loss: 0.0030 - precision: 0.9991 - recall: 0.9998 - val_accuracy: 0.9992 - val_loss: 0.0043 - val_precision: 0.9984 - val_recall: 1.0000
Epoch 31/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9994 - loss: 0.0029 - precision: 0.9990 - recall: 0.9999 - val_accuracy: 0.9992 - val_loss: 0.0043 - val_precision: 0.9984 - val_recall: 1.0000
Epoch 32/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9995 - loss: 0.0029 - precision: 0.9991 - recall: 0.9999 - val_accuracy: 0.9992 - val_loss: 0.0043 - val_precision: 0.9984 - val_recall: 1.0000
Epoch 33/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9995 - loss: 0.0028 - precision: 0.9992 - recall: 0.9999 - val_accuracy: 0.9989 - val_loss: 0.0050 - val_precision: 0.9989 - val_recall: 0.9990
Epoch 34/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9995 - loss: 0.0027 - precision: 0.9992 - recall: 0.9999 - val_accuracy: 0.9994 - val_loss: 0.0040 - val_precision: 0.9987 - val_recall: 1.0000
Epoch 35/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9995 - loss: 0.0027 - precision: 0.9992 - recall: 0.9999 - val_accuracy: 0.9992 - val_loss: 0.0044 - val_precision: 0.9983 - val_recall: 1.0000
Epoch 36/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - accuracy: 0.9995 - loss: 0.0026 - precision: 0.9992 - recall: 0.9999 - val_accuracy: 0.9994 - val_loss: 0.0041 - val_precision: 0.9989 - val_recall: 0.9999
Epoch 37/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9996 - loss: 0.0025 - precision: 0.9992 - recall: 0.9999 - val_accuracy: 0.9992 - val_loss: 0.0043 - val_precision: 0.9984 - val_recall: 1.0000
Epoch 38/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9996 - loss: 0.0025 - precision: 0.9992 - recall: 0.9999 - val_accuracy: 0.9993 - val_loss: 0.0040 - val_precision: 0.9986 - val_recall: 1.0000
Epoch 39/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9996 - loss: 0.0024 - precision: 0.9993 - recall: 0.9999 - val_accuracy: 0.9993 - val_loss: 0.0041 - val_precision: 0.9987 - val_recall: 1.0000
Epoch 40/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9996 - loss: 0.0024 - precision: 0.9993 - recall: 0.9999 - val_accuracy: 0.9994 - val_loss: 0.0038 - val_precision: 0.9988 - val_recall: 1.0000
Epoch 41/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - accuracy: 0.9996 - loss: 0.0024 - precision: 0.9993 - recall: 0.9999 - val_accuracy: 0.9993 - val_loss: 0.0041 - val_precision: 0.9985 - val_recall: 1.0000
Epoch 42/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - accuracy: 0.9996 - loss: 0.0023 - precision: 0.9993 - recall: 0.9999 - val_accuracy: 0.9994 - val_loss: 0.0039 - val_precision: 0.9987 - val_recall: 1.0000
Epoch 43/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - accuracy: 0.9997 - loss: 0.0023 - precision: 0.9994 - recall: 1.0000 - val_accuracy: 0.9992 - val_loss: 0.0041 - val_precision: 0.9984 - val_recall: 1.0000
Epoch 44/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9997 - loss: 0.0022 - precision: 0.9994 - recall: 0.9999 - val_accuracy: 0.9994 - val_loss: 0.0039 - val_precision: 0.9989 - val_recall: 1.0000
Epoch 45/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - accuracy: 0.9996 - loss: 0.0022 - precision: 0.9994 - recall: 0.9999 - val_accuracy: 0.9994 - val_loss: 0.0038 - val_precision: 0.9987 - val_recall: 1.0000
Epoch 46/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - accuracy: 0.9997 - loss: 0.0022 - precision: 0.9994 - recall: 1.0000 - val_accuracy: 0.9993 - val_loss: 0.0039 - val_precision: 0.9987 - val_recall: 1.0000
Epoch 47/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 17s 7ms/step - accuracy: 0.9997 - loss: 0.0021 - precision: 0.9994 - recall: 0.9999 - val_accuracy: 0.9993 - val_loss: 0.0041 - val_precision: 0.9985 - val_recall: 1.0000
Epoch 48/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9997 - loss: 0.0021 - precision: 0.9995 - recall: 0.9999 - val_accuracy: 0.9994 - val_loss: 0.0036 - val_precision: 0.9988 - val_recall: 1.0000
Epoch 49/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - accuracy: 0.9997 - loss: 0.0020 - precision: 0.9995 - recall: 0.9999 - val_accuracy: 0.9993 - val_loss: 0.0038 - val_precision: 0.9987 - val_recall: 1.0000
Epoch 50/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - accuracy: 0.9997 - loss: 0.0021 - precision: 0.9995 - recall: 0.9999 - val_accuracy: 0.9994 - val_loss: 0.0037 - val_precision: 0.9988 - val_recall: 1.0000

## Model 3 Fitting

In [43]:
model3_100 = create_model("relu","rmsprop")

model3_100.fit(
    stscaled_train,
    y_train,
    epochs=100,
    validation_data=(stscaled_val,y_val),
    batch_size=128

)

Epoch 1/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - accuracy: 0.9896 - loss: 0.0323 - precision: 0.9935 - recall: 0.9856 - val_accuracy: 0.9973 - val_loss: 0.0088 - val_precision: 0.9977 - val_recall: 0.9970
Epoch 2/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9982 - loss: 0.0072 - precision: 0.9975 - recall: 0.9989 - val_accuracy: 0.9991 - val_loss: 0.0049 - val_precision: 0.9987 - val_recall: 0.9994
Epoch 3/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - accuracy: 0.9987 - loss: 0.0053 - precision: 0.9982 - recall: 0.9992 - val_accuracy: 0.9990 - val_loss: 0.0048 - val_precision: 0.9979 - val_recall: 1.0000
Epoch 4/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9989 - loss: 0.0045 - precision: 0.9985 - recall: 0.9994 - val_accuracy: 0.9987 - val_loss: 0.0053 - val_precision: 0.9990 - val_recall: 0.9984
Epoch 5/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - accuracy: 0.9990 - loss: 0.0042 - precision: 0.9987 - recall: 0.9994 - val_accuracy: 0.9991 - val_loss: 0.0043 - val_precision: 0.9983 - val_recall: 0.9999
Epoch 6/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9991 - loss: 0.0038 - precision: 0.9988 - recall: 0.9994 - val_accuracy: 0.9988 - val_loss: 0.0059 - val_precision: 0.9976 - val_recall: 1.0000
Epoch 7/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - accuracy: 0.9991 - loss: 0.0042 - precision: 0.9987 - recall: 0.9995 - val_accuracy: 0.9982 - val_loss: 0.0116 - val_precision: 0.9990 - val_recall: 0.9974
Epoch 8/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 17s 7ms/step - accuracy: 0.9991 - loss: 0.0038 - precision: 0.9988 - recall: 0.9995 - val_accuracy: 0.9988 - val_loss: 0.0059 - val_precision: 0.9977 - val_recall: 1.0000
Epoch 9/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 22s 8ms/step - accuracy: 0.9992 - loss: 0.0038 - precision: 0.9988 - recall: 0.9996 - val_accuracy: 0.9995 - val_loss: 0.0029 - val_precision: 0.9990 - val_recall: 1.0000
Epoch 10/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - accuracy: 0.9993 - loss: 0.0034 - precision: 0.9990 - recall: 0.9996 - val_accuracy: 0.9992 - val_loss: 0.0042 - val_precision: 0.9986 - val_recall: 0.9997
Epoch 11/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - accuracy: 0.9992 - loss: 0.0033 - precision: 0.9989 - recall: 0.9996 - val_accuracy: 0.9992 - val_loss: 0.0038 - val_precision: 0.9987 - val_recall: 0.9997
Epoch 12/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - accuracy: 0.9993 - loss: 0.0032 - precision: 0.9990 - recall: 0.9996 - val_accuracy: 0.9989 - val_loss: 0.0088 - val_precision: 0.9977 - val_recall: 1.0000
Epoch 13/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - accuracy: 0.9992 - loss: 0.0033 - precision: 0.9989 - recall: 0.9996 - val_accuracy: 0.9994 - val_loss: 0.0032 - val_precision: 0.9989 - val_recall: 0.9999
Epoch 14/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 17s 7ms/step - accuracy: 0.9991 - loss: 0.0034 - precision: 0.9987 - recall: 0.9995 - val_accuracy: 0.9995 - val_loss: 0.0034 - val_precision: 0.9991 - val_recall: 0.9998
Epoch 15/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - accuracy: 0.9992 - loss: 0.0030 - precision: 0.9989 - recall: 0.9996 - val_accuracy: 0.9994 - val_loss: 0.0032 - val_precision: 0.9989 - val_recall: 1.0000
Epoch 16/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - accuracy: 0.9993 - loss: 0.0029 - precision: 0.9990 - recall: 0.9997 - val_accuracy: 0.9992 - val_loss: 0.0037 - val_precision: 0.9985 - val_recall: 1.0000
Epoch 17/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9993 - loss: 0.0031 - precision: 0.9988 - recall: 0.9997 - val_accuracy: 0.9990 - val_loss: 0.0053 - val_precision: 0.9980 - val_recall: 1.0000
Epoch 18/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - accuracy: 0.9992 - loss: 0.0031 - precision: 0.9988 - recall: 0.9996 - val_accuracy: 0.9991 - val_loss: 0.0039 - val_precision: 0.9981 - val_recall: 1.0000
Epoch 19/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - accuracy: 0.9993 - loss: 0.0029 - precision: 0.9989 - recall: 0.9997 - val_accuracy: 0.9991 - val_loss: 0.0041 - val_precision: 0.9984 - val_recall: 0.9998
Epoch 20/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - accuracy: 0.9994 - loss: 0.0026 - precision: 0.9990 - recall: 0.9998 - val_accuracy: 0.9994 - val_loss: 0.0035 - val_precision: 0.9987 - val_recall: 1.0000
Epoch 21/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9995 - loss: 0.0024 - precision: 0.9991 - recall: 0.9998 - val_accuracy: 0.9993 - val_loss: 0.0039 - val_precision: 0.9985 - val_recall: 1.0000
Epoch 22/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 21s 5ms/step - accuracy: 0.9995 - loss: 0.0022 - precision: 0.9992 - recall: 0.9998 - val_accuracy: 0.9993 - val_loss: 0.0041 - val_precision: 0.9987 - val_recall: 1.0000
Epoch 23/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9995 - loss: 0.0024 - precision: 0.9992 - recall: 0.9998 - val_accuracy: 0.9986 - val_loss: 0.0076 - val_precision: 0.9973 - val_recall: 1.0000
Epoch 24/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9995 - loss: 0.0022 - precision: 0.9992 - recall: 0.9998 - val_accuracy: 0.9995 - val_loss: 0.0030 - val_precision: 0.9990 - val_recall: 1.0000
Epoch 25/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9995 - loss: 0.0022 - precision: 0.9992 - recall: 0.9998 - val_accuracy: 0.9993 - val_loss: 0.0038 - val_precision: 0.9985 - val_recall: 1.0000
Epoch 26/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 20s 5ms/step - accuracy: 0.9995 - loss: 0.0024 - precision: 0.9992 - recall: 0.9998 - val_accuracy: 0.9992 - val_loss: 0.0046 - val_precision: 0.9985 - val_recall: 0.9999
Epoch 27/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - accuracy: 0.9996 - loss: 0.0021 - precision: 0.9994 - recall: 0.9998 - val_accuracy: 0.9993 - val_loss: 0.0048 - val_precision: 0.9986 - val_recall: 1.0000
Epoch 28/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - accuracy: 0.9995 - loss: 0.0021 - precision: 0.9993 - recall: 0.9998 - val_accuracy: 0.9990 - val_loss: 0.0057 - val_precision: 0.9990 - val_recall: 0.9991
Epoch 29/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9996 - loss: 0.0020 - precision: 0.9994 - recall: 0.9998 - val_accuracy: 0.9994 - val_loss: 0.0036 - val_precision: 0.9988 - val_recall: 1.0000
Epoch 30/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 18s 7ms/step - accuracy: 0.9996 - loss: 0.0020 - precision: 0.9994 - recall: 0.9998 - val_accuracy: 0.9993 - val_loss: 0.0031 - val_precision: 0.9990 - val_recall: 0.9997
Epoch 31/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - accuracy: 0.9996 - loss: 0.0021 - precision: 0.9994 - recall: 0.9998 - val_accuracy: 0.9991 - val_loss: 0.0058 - val_precision: 0.9982 - val_recall: 1.0000
Epoch 32/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - accuracy: 0.9996 - loss: 0.0022 - precision: 0.9994 - recall: 0.9998 - val_accuracy: 0.9994 - val_loss: 0.0034 - val_precision: 0.9988 - val_recall: 1.0000
Epoch 33/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - accuracy: 0.9996 - loss: 0.0019 - precision: 0.9995 - recall: 0.9998 - val_accuracy: 0.9995 - val_loss: 0.0035 - val_precision: 0.9992 - val_recall: 0.9999
Epoch 34/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - accuracy: 0.9997 - loss: 0.0017 - precision: 0.9995 - recall: 0.9998 - val_accuracy: 0.9993 - val_loss: 0.0039 - val_precision: 0.9987 - val_recall: 1.0000
Epoch 35/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - accuracy: 0.9997 - loss: 0.0016 - precision: 0.9995 - recall: 0.9999 - val_accuracy: 0.9994 - val_loss: 0.0032 - val_precision: 0.9989 - val_recall: 1.0000
Epoch 36/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - accuracy: 0.9997 - loss: 0.0018 - precision: 0.9995 - recall: 0.9999 - val_accuracy: 0.9994 - val_loss: 0.0037 - val_precision: 0.9987 - val_recall: 1.0000
Epoch 37/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 19s 5ms/step - accuracy: 0.9997 - loss: 0.0013 - precision: 0.9996 - recall: 0.9998 - val_accuracy: 0.9990 - val_loss: 0.0115 - val_precision: 0.9989 - val_recall: 0.9991
Epoch 38/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9997 - loss: 0.0021 - precision: 0.9995 - recall: 0.9998 - val_accuracy: 0.9994 - val_loss: 0.0039 - val_precision: 0.9989 - val_recall: 1.0000
Epoch 39/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - accuracy: 0.9997 - loss: 0.0018 - precision: 0.9996 - recall: 0.9998 - val_accuracy: 0.9995 - val_loss: 0.0027 - val_precision: 0.9991 - val_recall: 1.0000
Epoch 40/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - accuracy: 0.9997 - loss: 0.0015 - precision: 0.9996 - recall: 0.9998 - val_accuracy: 0.9994 - val_loss: 0.0046 - val_precision: 0.9989 - val_recall: 0.9998
Epoch 41/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9997 - loss: 0.0016 - precision: 0.9997 - recall: 0.9998 - val_accuracy: 0.9995 - val_loss: 0.0033 - val_precision: 0.9991 - val_recall: 0.9999
Epoch 42/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9998 - loss: 0.0011 - precision: 0.9997 - recall: 0.9998 - val_accuracy: 0.9995 - val_loss: 0.0034 - val_precision: 0.9991 - val_recall: 1.0000
Epoch 43/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - accuracy: 0.9997 - loss: 0.0015 - precision: 0.9997 - recall: 0.9998 - val_accuracy: 0.9994 - val_loss: 0.0033 - val_precision: 0.9990 - val_recall: 0.9999
Epoch 44/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - accuracy: 0.9998 - loss: 0.0011 - precision: 0.9998 - recall: 0.9999 - val_accuracy: 0.9994 - val_loss: 0.0051 - val_precision: 0.9988 - val_recall: 1.0000
Epoch 45/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - accuracy: 0.9998 - loss: 0.0012 - precision: 0.9998 - recall: 0.9998 - val_accuracy: 0.9995 - val_loss: 0.0038 - val_precision: 0.9989 - val_recall: 1.0000
Epoch 46/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9998 - loss: 0.0014 - precision: 0.9997 - recall: 0.9999 - val_accuracy: 0.9993 - val_loss: 0.0048 - val_precision: 0.9987 - val_recall: 1.0000
Epoch 47/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - accuracy: 0.9997 - loss: 0.0016 - precision: 0.9996 - recall: 0.9999 - val_accuracy: 0.9994 - val_loss: 0.0039 - val_precision: 0.9989 - val_recall: 1.0000
Epoch 48/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - accuracy: 0.9998 - loss: 0.0011 - precision: 0.9997 - recall: 0.9999 - val_accuracy: 0.9993 - val_loss: 0.0046 - val_precision: 0.9987 - val_recall: 1.0000
Epoch 49/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - accuracy: 0.9998 - loss: 0.0011 - precision: 0.9997 - recall: 0.9998 - val_accuracy: 0.9996 - val_loss: 0.0027 - val_precision: 0.9991 - val_recall: 1.0000
Epoch 50/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9997 - loss: 0.0015 - precision: 0.9996 - recall: 0.9998 - val_accuracy: 0.9996 - val_loss: 0.0025 - val_precision: 0.9993 - val_recall: 0.9999
Epoch 51/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9997 - loss: 0.0013 - precision: 0.9996 - recall: 0.9998 - val_accuracy: 0.9995 - val_loss: 0.0034 - val_precision: 0.9989 - val_recall: 1.0000
Epoch 52/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - accuracy: 0.9997 - loss: 0.0016 - precision: 0.9996 - recall: 0.9998 - val_accuracy: 0.9993 - val_loss: 0.0045 - val_precision: 0.9988 - val_recall: 0.9999
Epoch 53/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9997 - loss: 0.0019 - precision: 0.9996 - recall: 0.9998 - val_accuracy: 0.9993 - val_loss: 0.0045 - val_precision: 0.9986 - val_recall: 1.0000
Epoch 54/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9996 - loss: 0.0019 - precision: 0.9995 - recall: 0.9998 - val_accuracy: 0.9994 - val_loss: 0.0036 - val_precision: 0.9989 - val_recall: 1.0000
Epoch 55/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9996 - loss: 0.0019 - precision: 0.9994 - recall: 0.9998 - val_accuracy: 0.9994 - val_loss: 0.0043 - val_precision: 0.9989 - val_recall: 1.0000
Epoch 56/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9997 - loss: 0.0016 - precision: 0.9996 - recall: 0.9999 - val_accuracy: 0.9970 - val_loss: 0.0158 - val_precision: 0.9994 - val_recall: 0.9945
Epoch 57/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9996 - loss: 0.0019 - precision: 0.9995 - recall: 0.9998 - val_accuracy: 0.9993 - val_loss: 0.0056 - val_precision: 0.9986 - val_recall: 1.0000
Epoch 58/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9997 - loss: 0.0017 - precision: 0.9995 - recall: 0.9998 - val_accuracy: 0.9993 - val_loss: 0.0058 - val_precision: 0.9987 - val_recall: 1.0000
Epoch 59/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9996 - loss: 0.0021 - precision: 0.9994 - recall: 0.9998 - val_accuracy: 0.9992 - val_loss: 0.0040 - val_precision: 0.9985 - val_recall: 1.0000
Epoch 60/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9996 - loss: 0.0024 - precision: 0.9994 - recall: 0.9997 - val_accuracy: 0.9996 - val_loss: 0.0029 - val_precision: 0.9992 - val_recall: 0.9999
Epoch 61/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9996 - loss: 0.0022 - precision: 0.9994 - recall: 0.9998 - val_accuracy: 0.9993 - val_loss: 0.0037 - val_precision: 0.9987 - val_recall: 1.0000
Epoch 62/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9995 - loss: 0.0024 - precision: 0.9993 - recall: 0.9998 - val_accuracy: 0.9991 - val_loss: 0.0045 - val_precision: 0.9982 - val_recall: 1.0000
Epoch 63/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9996 - loss: 0.0025 - precision: 0.9994 - recall: 0.9997 - val_accuracy: 0.9991 - val_loss: 0.0062 - val_precision: 0.9982 - val_recall: 1.0000
Epoch 64/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9996 - loss: 0.0024 - precision: 0.9994 - recall: 0.9998 - val_accuracy: 0.9994 - val_loss: 0.0035 - val_precision: 0.9987 - val_recall: 1.0000
Epoch 65/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9996 - loss: 0.0020 - precision: 0.9995 - recall: 0.9997 - val_accuracy: 0.9995 - val_loss: 0.0033 - val_precision: 0.9991 - val_recall: 1.0000
Epoch 66/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9997 - loss: 0.0019 - precision: 0.9996 - recall: 0.9998 - val_accuracy: 0.9995 - val_loss: 0.0039 - val_precision: 0.9990 - val_recall: 1.0000
Epoch 67/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9997 - loss: 0.0020 - precision: 0.9996 - recall: 0.9998 - val_accuracy: 0.9996 - val_loss: 0.0043 - val_precision: 0.9991 - val_recall: 1.0000
Epoch 68/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9997 - loss: 0.0016 - precision: 0.9996 - recall: 0.9998 - val_accuracy: 0.9994 - val_loss: 0.0071 - val_precision: 0.9988 - val_recall: 1.0000
Epoch 69/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9996 - loss: 0.0027 - precision: 0.9995 - recall: 0.9998 - val_accuracy: 0.9996 - val_loss: 0.0034 - val_precision: 0.9992 - val_recall: 1.0000
Epoch 70/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9997 - loss: 0.0022 - precision: 0.9996 - recall: 0.9998 - val_accuracy: 0.9994 - val_loss: 0.0051 - val_precision: 0.9991 - val_recall: 0.9997
Epoch 71/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9997 - loss: 0.0017 - precision: 0.9997 - recall: 0.9998 - val_accuracy: 0.9995 - val_loss: 0.0043 - val_precision: 0.9994 - val_recall: 0.9996
Epoch 72/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9998 - loss: 0.0016 - precision: 0.9997 - recall: 0.9999 - val_accuracy: 0.9996 - val_loss: 0.0040 - val_precision: 0.9991 - val_recall: 1.0000
Epoch 73/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9998 - loss: 0.0016 - precision: 0.9997 - recall: 0.9998 - val_accuracy: 0.9996 - val_loss: 0.0038 - val_precision: 0.9992 - val_recall: 1.0000
Epoch 74/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9998 - loss: 0.0013 - precision: 0.9997 - recall: 0.9998 - val_accuracy: 0.9994 - val_loss: 0.0066 - val_precision: 0.9987 - val_recall: 1.0000
Epoch 75/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9998 - loss: 8.9816e-04 - precision: 0.9997 - recall: 0.9999 - val_accuracy: 0.9994 - val_loss: 0.0061 - val_precision: 0.9988 - val_recall: 1.0000
Epoch 76/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9998 - loss: 0.0014 - precision: 0.9997 - recall: 0.9999 - val_accuracy: 0.9995 - val_loss: 0.0057 - val_precision: 0.9991 - val_recall: 0.9999
Epoch 77/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9998 - loss: 0.0011 - precision: 0.9998 - recall: 0.9999 - val_accuracy: 0.9995 - val_loss: 0.0059 - val_precision: 0.9990 - val_recall: 0.9999
Epoch 78/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - accuracy: 0.9998 - loss: 0.0014 - precision: 0.9998 - recall: 0.9999 - val_accuracy: 0.9997 - val_loss: 0.0039 - val_precision: 0.9994 - val_recall: 0.9999
Epoch 79/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - accuracy: 0.9999 - loss: 8.2634e-04 - precision: 0.9998 - recall: 0.9999 - val_accuracy: 0.9997 - val_loss: 0.0042 - val_precision: 0.9993 - val_recall: 1.0000
Epoch 80/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - accuracy: 0.9998 - loss: 0.0011 - precision: 0.9998 - recall: 0.9999 - val_accuracy: 0.9997 - val_loss: 0.0060 - val_precision: 0.9994 - val_recall: 1.0000
Epoch 81/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - accuracy: 0.9998 - loss: 0.0017 - precision: 0.9997 - recall: 0.9998 - val_accuracy: 0.9995 - val_loss: 0.0058 - val_precision: 0.9989 - val_recall: 1.0000
Epoch 82/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - accuracy: 0.9998 - loss: 0.0012 - precision: 0.9997 - recall: 0.9998 - val_accuracy: 0.9996 - val_loss: 0.0042 - val_precision: 0.9993 - val_recall: 1.0000
Epoch 83/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 21s 5ms/step - accuracy: 0.9998 - loss: 0.0010 - precision: 0.9998 - recall: 0.9999 - val_accuracy: 0.9995 - val_loss: 0.0056 - val_precision: 0.9991 - val_recall: 1.0000
Epoch 84/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 21s 5ms/step - accuracy: 0.9998 - loss: 0.0011 - precision: 0.9997 - recall: 0.9999 - val_accuracy: 0.9992 - val_loss: 0.0107 - val_precision: 0.9984 - val_recall: 1.0000
Epoch 85/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - accuracy: 0.9998 - loss: 0.0012 - precision: 0.9998 - recall: 0.9999 - val_accuracy: 0.9995 - val_loss: 0.0054 - val_precision: 0.9990 - val_recall: 1.0000
Epoch 86/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9998 - loss: 8.9895e-04 - precision: 0.9998 - recall: 0.9998 - val_accuracy: 0.9996 - val_loss: 0.0034 - val_precision: 0.9993 - val_recall: 0.9998
Epoch 87/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - accuracy: 0.9998 - loss: 0.0010 - precision: 0.9997 - recall: 0.9998 - val_accuracy: 0.9981 - val_loss: 0.0082 - val_precision: 0.9996 - val_recall: 0.9965
Epoch 88/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - accuracy: 0.9999 - loss: 7.6522e-04 - precision: 0.9998 - recall: 0.9999 - val_accuracy: 0.9996 - val_loss: 0.0043 - val_precision: 0.9992 - val_recall: 1.0000
Epoch 89/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - accuracy: 0.9999 - loss: 0.0012 - precision: 0.9998 - recall: 0.9999 - val_accuracy: 0.9995 - val_loss: 0.0061 - val_precision: 0.9990 - val_recall: 1.0000
Epoch 90/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9998 - loss: 9.2368e-04 - precision: 0.9998 - recall: 0.9999 - val_accuracy: 0.9995 - val_loss: 0.0080 - val_precision: 0.9990 - val_recall: 1.0000
Epoch 91/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 20s 5ms/step - accuracy: 0.9999 - loss: 7.1888e-04 - precision: 0.9999 - recall: 0.9999 - val_accuracy: 0.9995 - val_loss: 0.0065 - val_precision: 0.9989 - val_recall: 1.0000
Epoch 92/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - accuracy: 0.9999 - loss: 5.4197e-04 - precision: 0.9998 - recall: 0.9999 - val_accuracy: 0.9997 - val_loss: 0.0032 - val_precision: 0.9995 - val_recall: 0.9999
Epoch 93/100

## Model 4 Fitting

In [67]:
model4 = create_model("tanh","adam")

model4.fit(
    stscaled_train,
    y_train,
    epochs=30,
    validation_data=(stscaled_val,y_val),
    batch_size=128

)

Epoch 1/30
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - accuracy: 0.9853 - loss: 0.0413 - precision: 0.9891 - recall: 0.9814 - val_accuracy: 0.9931 - val_loss: 0.0199 - val_precision: 0.9929 - val_recall: 0.9932
Epoch 2/30
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9973 - loss: 0.0091 - precision: 0.9964 - recall: 0.9981 - val_accuracy: 0.9980 - val_loss: 0.0070 - val_precision: 0.9968 - val_recall: 0.9992
Epoch 3/30
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9984 - loss: 0.0058 - precision: 0.9978 - recall: 0.9990 - val_accuracy: 0.9989 - val_loss: 0.0050 - val_precision: 0.9978 - val_recall: 1.0000
Epoch 4/30
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9987 - loss: 0.0048 - precision: 0.9982 - recall: 0.9992 - val_accuracy: 0.9992 - val_loss: 0.0038 - val_precision: 0.9984 - val_recall: 1.0000
Epoch 5/30
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9992 - loss: 0.0035 - precision: 0.9988 - recall: 0.9995 - val_accuracy: 0.9993 - val_loss: 0.0038 - val_precision: 0.9986 - val_recall: 1.0000
Epoch 6/30
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9992 - loss: 0.0032 - precision: 0.9989 - recall: 0.9995 - val_accuracy: 0.9993 - val_loss: 0.0032 - val_precision: 0.9987 - val_recall: 0.9999
Epoch 7/30
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9994 - loss: 0.0026 - precision: 0.9991 - recall: 0.9996 - val_accuracy: 0.9995 - val_loss: 0.0026 - val_precision: 0.9991 - val_recall: 1.0000
Epoch 8/30
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9994 - loss: 0.0025 - precision: 0.9991 - recall: 0.9997 - val_accuracy: 0.9990 - val_loss: 0.0049 - val_precision: 0.9979 - val_recall: 1.0000
Epoch 9/30
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9995 - loss: 0.0025 - precision: 0.9992 - recall: 0.9998 - val_accuracy: 0.9996 - val_loss: 0.0025 - val_precision: 0.9992 - val_recall: 1.0000
Epoch 10/30
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9996 - loss: 0.0020 - precision: 0.9994 - recall: 0.9998 - val_accuracy: 0.9996 - val_loss: 0.0021 - val_precision: 0.9992 - val_recall: 1.0000
Epoch 11/30
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 21s 5ms/step - accuracy: 0.9996 - loss: 0.0020 - precision: 0.9994 - recall: 0.9998 - val_accuracy: 0.9996 - val_loss: 0.0025 - val_precision: 0.9994 - val_recall: 0.9998
Epoch 12/30
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - accuracy: 0.9996 - loss: 0.0019 - precision: 0.9994 - recall: 0.9998 - val_accuracy: 0.9988 - val_loss: 0.0049 - val_precision: 0.9977 - val_recall: 1.0000
Epoch 13/30
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - accuracy: 0.9996 - loss: 0.0019 - precision: 0.9994 - recall: 0.9998 - val_accuracy: 0.9997 - val_loss: 0.0021 - val_precision: 0.9995 - val_recall: 1.0000
Epoch 14/30
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9997 - loss: 0.0017 - precision: 0.9995 - recall: 0.9998 - val_accuracy: 0.9996 - val_loss: 0.0022 - val_precision: 0.9993 - val_recall: 1.0000
Epoch 15/30
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - accuracy: 0.9997 - loss: 0.0017 - precision: 0.9995 - recall: 0.9999 - val_accuracy: 0.9995 - val_loss: 0.0025 - val_precision: 0.9991 - val_recall: 1.0000
Epoch 16/30
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - accuracy: 0.9997 - loss: 0.0018 - precision: 0.9995 - recall: 0.9998 - val_accuracy: 0.9990 - val_loss: 0.0044 - val_precision: 0.9995 - val_recall: 0.9985
Epoch 17/30
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9997 - loss: 0.0017 - precision: 0.9995 - recall: 0.9998 - val_accuracy: 0.9996 - val_loss: 0.0024 - val_precision: 0.9992 - val_recall: 1.0000
Epoch 18/30
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9998 - loss: 0.0014 - precision: 0.9996 - recall: 0.9999 - val_accuracy: 0.9996 - val_loss: 0.0023 - val_precision: 0.9992 - val_recall: 1.0000
Epoch 19/30
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - accuracy: 0.9997 - loss: 0.0017 - precision: 0.9996 - recall: 0.9998 - val_accuracy: 0.9995 - val_loss: 0.0025 - val_precision: 0.9992 - val_recall: 0.9998
Epoch 20/30
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - accuracy: 0.9997 - loss: 0.0016 - precision: 0.9996 - recall: 0.9998 - val_accuracy: 0.9995 - val_loss: 0.0026 - val_precision: 0.9990 - val_recall: 1.0000
Epoch 21/30
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9997 - loss: 0.0015 - precision: 0.9996 - recall: 0.9999 - val_accuracy: 0.9995 - val_loss: 0.0027 - val_precision: 0.9989 - val_recall: 1.0000
Epoch 22/30
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - accuracy: 0.9997 - loss: 0.0015 - precision: 0.9996 - recall: 0.9999 - val_accuracy: 0.9996 - val_loss: 0.0022 - val_precision: 0.9992 - val_recall: 1.0000
Epoch 23/30
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - accuracy: 0.9997 - loss: 0.0014 - precision: 0.9996 - recall: 0.9999 - val_accuracy: 0.9995 - val_loss: 0.0025 - val_precision: 0.9990 - val_recall: 1.0000
Epoch 24/30
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - accuracy: 0.9997 - loss: 0.0014 - precision: 0.9996 - recall: 0.9999 - val_accuracy: 0.9996 - val_loss: 0.0026 - val_precision: 0.9992 - val_recall: 1.0000
Epoch 25/30
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - accuracy: 0.9998 - loss: 0.0012 - precision: 0.9997 - recall: 0.9999 - val_accuracy: 0.9992 - val_loss: 0.0037 - val_precision: 0.9994 - val_recall: 0.9990
Epoch 26/30
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9998 - loss: 0.0013 - precision: 0.9996 - recall: 0.9999 - val_accuracy: 0.9996 - val_loss: 0.0021 - val_precision: 0.9993 - val_recall: 1.0000
Epoch 27/30
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - accuracy: 0.9998 - loss: 0.0014 - precision: 0.9997 - recall: 0.9999 - val_accuracy: 0.9996 - val_loss: 0.0023 - val_precision: 0.9992 - val_recall: 1.0000
Epoch 28/30
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - accuracy: 0.9997 - loss: 0.0014 - precision: 0.9996 - recall: 0.9999 - val_accuracy: 0.9995 - val_loss: 0.0025 - val_precision: 0.9991 - val_recall: 1.0000
Epoch 29/30
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - accuracy: 0.9998 - loss: 0.0013 - precision: 0.9997 - recall: 0.9999 - val_accuracy: 0.9996 - val_loss: 0.0023 - val_precision: 0.9993 - val_recall: 1.0000
Epoch 30/30
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - accuracy: 0.9997 - loss: 0.0014 - precision: 0.9996 - recall: 0.9999 - val_accuracy: 0.9996 - val_loss: 0.0021 - val_precision: 0.9993 - val_recall: 1.0000

model_ar,adam,batch_size=64

In [61]:
#Epoch 20/20
#5312/5312 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - accuracy: 0.9996 - loss: 0.0013 - precision: 0.9992 - recall: 0.9997 - val_accuracy: 1.0000 - val_loss: 3.5467e-04 - val_precision: 1.0000 - val_recall: 1.0000

model_ar,adam,batch_size=128

In [62]:
#Epoch 20/20
#2656/2656 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - accuracy: 0.9999 - loss: 4.6336e-04 - precision: 0.9998 - recall: 0.9999 - val_accuracy: 1.0000 - val_loss: 8.6220e-05 - val_precision: 1.0000 - val_recall: 1.0000

model_ar,adam,batch_size=256

In [63]:
#Epoch 20/20
#1328/1328 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.9999 - loss: 2.3872e-04 - precision: 0.9999 - recall: 0.9999 - val_accuracy: 0.9996 - val_loss: 0.0011 - val_precision: 1.0000 - val_recall: 0.9996

Lets the best results,according to the val_accuracy and others with relation to the training accuracy,The best batch size is 128 for this model.

## Model prediction on unseen(test) Data

#### Predictions For Model 1

In [64]:
# y_pred1_20=model1_20.predict(stscaled_test)
# y_pred1_20=(y_pred1_20 >=0.5).astype(int).ravel()   #astype(int) can converts it to 0 and 1 ,and ravel can convert it into 1D array

#It exactly like this
#y_pred = [1 if prob[0] >= 0.5 else 0 for p in y_pred1_20]
#prob[0] can picks our number at there
# prob       → [0.23]
# prob[0]    → 0.23

In [49]:
y_pred1_50=model1_50.predict(stscaled_test)
y_pred1_50=(y_pred1_50 >=0.6).astype(int).ravel()

# y_prob = model1_50.predict(stscaled_test).ravel()

# for threshold in [0.3, 0.4, 0.5, 0.6, 0.7]:
#     y_pred = (y_prob >= threshold).astype(int)

#     print("Threshold:", threshold)
#     print("Precision:", precision_score(y_test, y_pred, zero_division=0))
#     print("Recall:", recall_score(y_test, y_pred, zero_division=0))
#     print("F1:", f1_score(y_test, y_pred, zero_division=0))
#     print()

2217/2217 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step

#### Predictions For Model 2

In [50]:
y_pred2_50=model2_50.predict(stscaled_test)
y_pred2_50=(y_pred2_50 >= 0.6).astype(int).ravel()

2217/2217 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step

#### Predictions For Model 3

In [51]:
y_pred3_100=model3_100.predict(stscaled_test)
y_pred3_100=(y_pred3_100 >= 0.6).astype(int).ravel()

2217/2217 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step

### Predictions For Model 4

In [68]:
y_pred4=model4.predict(stscaled_test)
y_pred4=(y_pred4 >= 0.6).astype(int).ravel()

2217/2217 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step

## Finding confusion_matrix,accuracy_score,precision_score,recall_score,f1_score

In [53]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,f1_score

# For Model 1

In [54]:
#With 20 Epochs
# accuracy1_20 = accuracy_score(y_test, y_pred1_20)
# precision1_20 = precision_score(y_test, y_pred1_20)
# recall1_20 = recall_score(y_test, y_pred1_20)
# f1_1_20 = f1_score(y_test, y_pred1_20)
# confusion_matrix1_20=confusion_matrix(y_test,y_pred1_20)

In [55]:
#With 50 Epochs
accuracy1_50 = accuracy_score(y_test, y_pred1_50)
precision1_50 = precision_score(y_test, y_pred1_50)
recall1_50 = recall_score(y_test, y_pred1_50)
f1_1_50 = f1_score(y_test, y_pred1_50)
confusion_matrix1_50=confusion_matrix(y_test,y_pred1_50)

# For Model 2

In [56]:
#With 50 Epochs
accuracy2_50 = accuracy_score(y_test, y_pred2_50)
precision2_50 = precision_score(y_test, y_pred2_50)
recall2_50 = recall_score(y_test, y_pred2_50)
f1_2_50 = f1_score(y_test, y_pred2_50)
confusion_matrix2_50=confusion_matrix(y_test,y_pred2_50)

# For Model 3

In [57]:
#With 100 Epochs
accuracy3_100 = accuracy_score(y_test, y_pred3_100)
precision3_100 = precision_score(y_test, y_pred3_100)
recall3_100 = recall_score(y_test, y_pred3_100)
f1_3_100 = f1_score(y_test, y_pred3_100)
confusion_matrix3_100=confusion_matrix(y_test,y_pred3_100)

# Model 4

In [69]:
accuracy4 = accuracy_score(y_test, y_pred4)
precision4 = precision_score(y_test, y_pred4)
recall4 = recall_score(y_test, y_pred4)
f1_4 = f1_score(y_test, y_pred4)
confusion_matrix4=confusion_matrix(y_test,y_pred4)

### Models Results:

In [59]:
#Model 1
print(accuracy1_50)
print(precision1_50)
print(recall1_50)
print(f1_1_50)

0.9994078836068347
0.8203125
0.8467741935483871
0.8333333333333334

In [60]:
#model 1
print(confusion_matrix1_50)  #CONFUSION MATRIX

[[70785    23]
 [   19   105]]

In [61]:
#model 2 
print(accuracy2_50)
print(precision2_50)
print(recall2_50)
print(f1_2_50)

0.9986747871200586
0.5824175824175825
0.8548387096774194
0.6928104575163399

In [62]:
#model 2   #CONFUSION MATRIX
print(confusion_matrix2_50)

[[70732    76]
 [   18   106]]

In [63]:
#model 3
print(accuracy3_100)
print(precision3_100)
print(recall3_100)
print(f1_3_100)

0.99908362939153
0.7006802721088435
0.8306451612903226
0.7601476014760148

In [64]:
#Model 3    #CONFUSON MATRIX
print(confusion_matrix3_100)

[[70764    44]
 [   21   103]]

In [70]:
#Model 4
print(accuracy4)
print(precision4)
print(recall4)
print(f1_4)

0.999097727400891
0.6973684210526315
0.8548387096774194
0.7681159420289855

In [71]:
print(confusion_matrix4)

[[70762    46]
 [   18   106]]

## Models Comparasion Chart:

In [73]:
pd.DataFrame({"Model":["Model 1","Model 2","Model 3","Model 4"],"Activation":["Relu","Tanh","Relu","tanh"],"Optimizer":["Adam","SGD","RMSProp","adam"],"Epochs":[50,50,100,30],"Acuracy":[0.9994,0.9986,0.9984,0.9990],"Precision":[0.8203,0.5824,0.7006,0.6973],"Recall":[0.8467,0.8548,0.8306,0.8548],"F1_score":[0.8333,0.6928,0.7601,0.7681]})

     Model Activation Optimizer  Epochs  Acuracy  Precision  Recall  F1_score
0  Model 1       Relu      Adam      50   0.9994     0.8203  0.8467    0.8333
1  Model 2       Tanh       SGD      50   0.9986     0.5824  0.8548    0.6928
2  Model 3       Relu   RMSProp     100   0.9984     0.7006  0.8306    0.7601
3  Model 4       tanh      adam      30   0.9990     0.6973  0.8548    0.7681

### Prediction Samples

In [79]:
pd.DataFrame({"Actual":y_test[450:500],"Predicted":y_pred1_50[450:500]})

        Actual  Predicted
223600       0          0
140223       0          0
115516       0          0
154922       0          0
150901       0          0
12932        0          0
80171        0          0
71738        0          0
25274        0          0
183746       0          0
96257        0          0
196535       0          0
277157       0          0
28327        0          0
7082         0          0
163606       0          0
158446       0          0
53689        0          0
41162        0          0
157188       0          1
123416       0          0
47142        0          0
146653       0          0
245560       0          0
77512        0          0
262122       0          0
141450       0          0
257450       1          1
266921       0          0
93596        0          0
47929        0          0
51641        0          0
178950       0          0
79117        0          0
36920        0          0
33912        0          0
277720       0          0
145262       0          0
91765        0          0
212808       0          0
260261       0          0
258168       0          0
115171       0          0
8430         0          0
181100       0          0
251325       0          0
277674       0          0
230175       0          0
44889        0          0
141635       0          0

# Conclusion:

Model 1 (ReLU activation, Adam optimizer, 50 epochs) achieved the best overall performance, showing the highest accuracy (0.9994) and strong precision, recall, and F1 scores compared to the other models.